In [61]:
import pandas as pd
import numpy as np

In [62]:
df = pd.read_csv("/content/play_tennis.csv")

In [63]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [64]:
df.drop(["day"],inplace=True,axis=1)

In [65]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [66]:
## Problem 1

# Outlook = Sunny, Temp=Hot, Humididty = high and wind = weak
# should i play tennis or not?

In [67]:
## Solution

# P(Yes/Sunny,hot,high,weak) = P(Sunny/yes) * P(hot/yes) * P(high/yes) * P(wind/yes) * P(yes)
# P(no/Sunny,hot,high,weak) = P(Sunny/no)  * P(Hot/no) * P(high/no) *P(wind/no) * P(no)

# campare and decide using the maximum a posteriori rule

In [68]:
## Training in Naive Bayes
# - Creates a lookup table using dictionary - stores all possible probability

## Testing

In [69]:
(df['play'].value_counts())

play
Yes    9
No     5
Name: count, dtype: int64

In [70]:
# P(Y)
py = 9/14
# P(N)
pn = 5/14

In [71]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [72]:
## Outlook columns
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [73]:
## P(outlook)
POvercastYes= 4/9
PRainYes = 3/9
PSunnyYes = 2/9

## P(Outlook)
POvercastNo= 0
PRainNo = 2/5
PSunnyNo = 3/5

In [74]:
## temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [75]:
## Temp
PCoolYes = 3/9
PHotYes = 2/9
PMild = 4/9

## Temp (No)
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

In [76]:
# humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [77]:
## Humidity
PHighYes = 3/9
PNormalYes = 6/9

PHighNo = 4/5
PNormalNo = 1/5

In [78]:
## wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [79]:
## wind
PWeakYes = 6/9
PStrongYes = 3/9

PWeakNo = 2/5
PStrongNo = 3/5

In [80]:
# Outlook = Sunny, Temp=Hot, Humididty = high and wind = weak
Pyes = py*PSunnyYes*PHotYes*PHighYes*PWeakYes
print(Pyes)

0.007054673721340388

In [81]:
Pno = PSunnyNo*PHotNo*PHighNo*PWeakNo*pn
print(Pno)

0.02742857142857143

In [82]:
## Output = No, since Pno > Pyes